---
title: "Prelim_data_exploration"
author: "Nicole Hill"
date: "15/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Environmental Data

Requires first matching environmental data to image annotation data at cell level (Nic)

1) Density plots for each environmental variable  
2) correlation between environmental variables  
3) environmental coverage (jan's pretty shiny app!)  


###Image data

requires adding image quality index to images and date and camera platform and survey- Jan/ Charley

1) Distribution of area and image quality by: survey, institute, platform  
2) Distribution of number of images per cell  
3) Temporal (and spatial) distribution of images  
4) Histogram of Distance between images (need to think about how to avoid going over land)


## Biological Data

requires matching cell level annotations with environmental data (same as 1 above -Nic)  
Jan to add number of images/number of points to each cover/count at cell level file 

1) prevalence of each biological taxa (will help inform any aggregation)  
2) key taxa spatial bubbleplots  
3) Any platform -related effects??  
4) GAMS with env data



