---
title: "ROMS FAM 4km analysis"
author: "Jan Jansen"
date: "20/01/2022"
output: html_document
---

###########################################
########## Evaluate ROMS outputs ##########
###########################################

```{r setup, include=FALSE}
#### setup environment
library(raster)
library(colorspace)
library(viridis)
library(ncdf4)
library(raadtools)
library(rgdal)
## data-directories
env.dir <- "C:/Users/jjansen/Desktop/science/data_environmental/"
env.raw <- paste0(env.dir,"raw/")
env.derived <- paste0(env.dir,"derived/")
AAD_dir <- paste0(env.dir,"raw/accessed_through_R")
ARC_data_dir <- "C:/Users/jjansen/Desktop/science/SouthernOceanBiodiversityMapping/ARC_Data/"
ant.proj <- "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"
```

########## Prepare data ##########

```{r}
#### load non-ROMS data
## load projected coastline for plotting
load(paste0(env.derived,"Circumpolar_Coastline.Rdata"))
r2 <- raster(paste0(env.derived,"Circumpolar_EnvData_500m_shelf_bathy_gebco_depth.grd"))
## load circumpolar Diatom data
load(paste0(ARC_data_dir,"FAM/Circumpolar_Diatom_metadata.Rdata"))
## load Mertz Diatom data
mertz.diatom.dat <- read.csv("C:/Users/jjansen/Desktop/science/PhD/1 bentho-pelagic-coupling/DiatomAbundance.csv")
mertz.diatom.locs <- project(as.matrix(mertz.diatom.dat[,c(4,3)]),proj=ant.proj)

#### load ROMS-runs:
data.dat100 <- paste0(env.dir,"Circumpolar_ROMS/4km_outputs/output_sed_test1/")
# data.dat100 <- paste0(env.dir,"Circumpolar_ROMS/10km_outputs/output_sed_float_test3/")
# data.dat200 <- paste0(env.dir,"Circumpolar_ROMS/10km_outputs/output_sed_float_test4/")
# data.dat400 <- paste0(env.dir,"Circumpolar_ROMS/10km_outputs/output_sed_float_test5/")
# data.dat <- paste0("Circumpolar_ROMS/10km_outputs/sed_test1/")
# data.dat <- paste0(env.dir,"Circumpolar_ROMS/10km_outputs/sed_test5/")

#### load lon/lat information from ROMS-grid
grd4k_nc <- nc_open(paste0(env.raw,"waom4extend_grd.nc"))
lon_rho <- ncvar_get(grd4k_nc, varid="lon_rho")
lat_rho <- ncvar_get(grd4k_nc, varid="lat_rho")

#### Prepare empty rasters to assign correct projected values to
roms.coords.proj <- project(cbind(c(lon_rho), c(lat_rho)), proj=ant.proj)
x.range <- c(min(roms.coords.proj[,1])-2000,max(roms.coords.proj[,1])+2000)
y.range <- c(min(roms.coords.proj[,2])-2000,max(roms.coords.proj[,2])+2000)
empty.roms.ra <- raster(extent(c(x.range,y.range)), crs=ant.proj, resolution=4000)

#### load other ROMS data (currents & depth)
#depth
h <- raster(paste0(data.dat100,"ocean_avg_0001.nc"), varname="h", level=1)
#seafloor currents (seafloor-layer is 1)
u.raw <- brick(paste0(data.dat100,"ocean_his_0001.nc"), varname="u", level=1)
v.raw <- brick(paste0(data.dat100,"ocean_his_0001.nc"), varname="v", level=1)
#seasurface currents (surface-layer is 31)
u_31.raw <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="u", level=31)
v_31.raw <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="v", level=31)
## sum up monthly values for a climatology (THIS SHOULD BE DONE ON HIGH RESOLUTION HISTORY FILES)
u.sum <- sum(u.raw)
v.sum <- sum(v.raw)
u.sum.abs <- sum(abs(u.raw))
v.sum.abs <- sum(abs(v.raw))
u31.sum <- sum(u_31.raw)
v31.sum <- sum(v_31.raw)
## extract current speeds at rho-points where depth is defined
## (in ROMS they are all at different locations):
## u has one less column than the grid, so all coordinates need to be moved half a cell to the right for the grids to match up
coord.grd.u <- coordinates(h)
coord.grd.u[,1] <- coordinates(h)[,1]-0.5
## v has one less row than the grid, so all coordinates need to be moved half a cell up for the grids to match up
coord.grd.v <- coordinates(h)
coord.grd.v[,2] <- coordinates(h)[,2]-0.5
## now extract values at the rho-points and interpolate (because they are 2km away from the nearest original point), and place into projected raster
u <- v <- u.abs <- v.abs <- u31 <- v31 <- empty.roms.ra
u[] <- extract(u.sum, coord.grd.u, method="bilinear")
v[] <- extract(v.sum, coord.grd.v, method="bilinear")
u.abs[] <- extract(u.sum.abs, coord.grd.u, method="bilinear")
v.abs[] <- extract(v.sum.abs, coord.grd.v, method="bilinear")
u31[] <- extract(u31.sum, coord.grd.u, method="bilinear")
v31[] <- extract(v31.sum, coord.grd.v, method="bilinear")
#seasurface current speeds
uv_31 <- sqrt(u31^2+v31^2)
#temporal mean seafloor current speed
mean.uv <- sqrt(u^2+v^2)
#absolute mean seafloor current speed
abs.uv <- sqrt(u.abs^2+v.abs^2)
#residual seafloor current speed
res.uv <- abs.uv-mean.uv
## remove inland values for depth
h2 <- empty.roms.ra
h2[] <- h[]
h2[is.na(mean.uv)] <- NA

# #temporal mean seafloor current speed
# mean.u <- sum(u)
# mean.v <- sum(v)
# #absolute mean seafloor current speed
# abs.u <- sum(abs(u))
# abs.v <- sum(abs(v))
# #residual seafloor current speed
# res.u <- abs.u-mean.u
# res.v <- abs.v-mean.v
# mean.uv2 <- sqrt(mean.u^2+mean.v^2)
# abs.uv2 <- sqrt(abs.u^2+abs.v^2)
# res.uv2 <- abs.uv2-mean.uv2

```

########## Overview plots - Ocean currents ##########

```{r, fig.width=10, fig.height=10}
## ocean current data
#cols <- rev(terrain.colors(96))
cols <- rev(magma(96)) #12, 24, 48, 96
breaks <- seq(0,6,length.out=97)
par(mfrow=c(2,2))
plot(mean.uv, breaks=breaks, col=cols, main="seafloor currents - mean")
plot(abs.uv, breaks=breaks, col=cols, main="seafloor currents - absolute speed")
plot(res.uv, breaks=breaks, col=cols, main="seafloor currents - residual")
plot(uv_31, breaks=breaks, col=cols, main="seasurface currents")
## ocean current data in the Mertz region
cols <- rev(magma(84)) #12, 24, 48, 96
breaks <- seq(0,2.1,length.out=85)
xlim <- c(1300000,1900000)
ylim <- c(-2300000,-1900000)
par(mfrow=c(2,2))
plot(mean.uv, breaks=breaks, col=cols, main="seafloor currents - mean", xlim=xlim, ylim=ylim)
#plot(coast.proj, add=TRUE)
plot(abs.uv, breaks=breaks, col=cols, main="seafloor currents - absolute speed", xlim=xlim, ylim=ylim)
#plot(coast.proj, add=TRUE)
plot(res.uv, breaks=breaks, col=cols, main="seafloor currents - residual", xlim=xlim, ylim=ylim)
#plot(coast.proj, add=TRUE)
plot(h2, col=cols, main="depth", xlim=xlim, ylim=ylim)
#plot(coast.proj, add=TRUE)
```

########## EVALUATE FAM ##########

```{r, message=FALSE, warning=FALSE, results="hide"}
## values originally in kg/m2/s -> change to kg/m2/day (*86400)
### NOTE THAT CURRENTLY DIFFERENT MODEL RUNS HAVE ALL THE SAME OUTPUT APART FROM THE "ocean_flt.nc" file
surf_01 <- surf_02 <- surf_03 <- surf_04 <- surf_05 <- surf_06 <- surf_07 <- surf_08 <- brick(empty.roms.ra,nl=6)
susp_01 <- susp_02 <- susp_03 <- susp_04 <- susp_05 <- susp_06 <- susp_07 <- susp_08 <- brick(empty.roms.ra,nl=6)
settle_01 <- settle_02 <- settle_03 <- settle_04 <- settle_05 <- settle_06 <- settle_07 <- settle_08 <- brick(empty.roms.ra,nl=7)
## surface production
surf_01[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_01", level=31)[]*86400
surf_02[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_02", level=31)[]*86400
surf_03[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_03", level=31)[]*86400
surf_04[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_04", level=31)[]*86400
surf_05[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_05", level=31)[]*86400
surf_06[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_06", level=31)[]*86400
surf_07[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_07", level=31)[]*86400
surf_08[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_08", level=31)[]*86400
## bottom ocean layer
susp_01[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_01", level=1)[]*86400
susp_02[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_02", level=1)[]*86400
susp_03[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_03", level=1)[]*86400
susp_04[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_04", level=1)[]*86400
susp_05[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_05", level=1)[]*86400
susp_06[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_06", level=1)[]*86400
susp_07[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_07", level=1)[]*86400
susp_08[] <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="sand_08", level=1)[]*86400
## settled particles
settle_01[] <- brick(paste0(data.dat100,"ocean_his_0001.nc"), varname="sandfrac_01", level=1)[]*86400
settle_02[] <- brick(paste0(data.dat100,"ocean_his_0001.nc"), varname="sandfrac_02", level=1)[]*86400
settle_03[] <- brick(paste0(data.dat100,"ocean_his_0001.nc"), varname="sandfrac_03", level=1)[]*86400
settle_04[] <- brick(paste0(data.dat100,"ocean_his_0001.nc"), varname="sandfrac_04", level=1)[]*86400
settle_05[] <- brick(paste0(data.dat100,"ocean_his_0001.nc"), varname="sandfrac_05", level=1)[]*86400
settle_06[] <- brick(paste0(data.dat100,"ocean_his_0001.nc"), varname="sandfrac_06", level=1)[]*86400
settle_07[] <- brick(paste0(data.dat100,"ocean_his_0001.nc"), varname="sandfrac_07", level=1)[]*86400
settle_08[] <- brick(paste0(data.dat100,"ocean_his_0001.nc"), varname="sandfrac_08", level=1)[]*86400
## bedload u
#bedu_01 <- brick(paste0(data.dat100,"ocean_avg_0001.nc"), varname="bedload_Usand_01", level=31)

```

########## Overview plots - FAM ##########

# why the weird values in the sandfrac output?
i.e. not comparable to surface or suspended fraction

# is there a way to calculate flux along the seafloor?

```{r, fig.width=10, fig.height=10}
## surface productivity 
# plot(surf_08*86400, breaks=seq(0,0.24,length.out=25), col=rev(heat.colors(25)))
# #plot(susp_08*86400, breaks=seq(0,0.24,length.out=25), col=rev(heat.colors(25)))
# plot(susp_08*86400, breaks=round(seq(-0.1,0.24,length.out=35),3), col=c(rev(blues9),rev(heat.colors(25))))
# plot(settle_08*86400, breaks=c(10780,seq(10795,10810,length.out=25),10935), col=c("green",rev(heat.colors(24)),"black"))

#### comparisons
breaks1 <- seq(0,0.25,length.out=51)
breaks2 <- c(-0.5,round(seq(0,0.25,length.out=51),3))
#breaks3 <- c(10780,seq(10795,10810,length.out=25),10935)
breaks3 <- c(10795,seq(10800,10805,length.out=51))
cols1 <- rev(viridis(50))#rev(magma(48))
cols2 <- c("grey",rev(viridis(50)))
cols3 <- c("grey",rev(viridis(50)))
par(mfrow=c(3,3), mar=c(3,4,2,1))
plot(surf_08[[2]], breaks=breaks1, col=cols1, main=paste0("surf_08 ",names(surf_08)[2]))
plot(surf_08[[3]], breaks=breaks1, col=cols1, main=paste0("surf_08 ",names(surf_08)[3]))
plot(surf_08[[4]], breaks=breaks1, col=cols1, main=paste0("surf_08 ",names(surf_08)[4]))
plot(susp_08[[2]], breaks=breaks2, col=cols2, main=paste0("susp_08 ",names(susp_08)[2]))
plot(susp_08[[3]], breaks=breaks2, col=cols2, main=paste0("susp_08 ",names(susp_08)[3]))
plot(susp_08[[4]], breaks=breaks2, col=cols2, main=paste0("susp_08 ",names(susp_08)[4]))
plot(settle_08[[2]], breaks=breaks3, col=cols3, main=paste0("settle_08 ",names(settle_08)[2]))
plot(settle_08[[3]], breaks=breaks3, col=cols3, main=paste0("settle_08 ",names(settle_08)[3]))
plot(settle_08[[4]], breaks=breaks3, col=cols3, main=paste0("settle_08 ",names(settle_08)[4]))

#### comparisons Mertz
par(mfrow=c(3,3))
plot(surf_08[[2]], xlim=xlim, ylim=ylim, breaks=breaks1, col=cols1, main=paste0("surf_08 ",names(surf_08)[2]))
plot(surf_08[[3]], xlim=xlim, ylim=ylim, breaks=breaks1, col=cols1, main=paste0("surf_08 ",names(surf_08)[3]))
plot(surf_08[[4]], xlim=xlim, ylim=ylim, breaks=breaks1, col=cols1, main=paste0("surf_08 ",names(surf_08)[4]))
plot(susp_08[[2]], xlim=xlim, ylim=ylim, breaks=breaks2, col=cols2, main=paste0("susp_08 ",names(susp_08)[2]))
plot(susp_08[[3]], xlim=xlim, ylim=ylim, breaks=breaks2, col=cols2, main=paste0("susp_08 ",names(susp_08)[3]))
plot(susp_08[[4]], xlim=xlim, ylim=ylim, breaks=breaks2, col=cols2, main=paste0("susp_08 ",names(susp_08)[4]))
plot(settle_08[[2]], xlim=xlim, ylim=ylim, breaks=breaks3, col=cols3, main=paste0("settle_08 ",names(settle_08)[2]))
plot(settle_08[[3]], xlim=xlim, ylim=ylim, breaks=breaks3, col=cols3, main=paste0("settle_08 ",names(settle_08)[3]))
plot(settle_08[[4]], xlim=xlim, ylim=ylim, breaks=breaks3, col=cols3, main=paste0("settle_08 ",names(settle_08)[4]))

#### comparisons surf / sink / settle for Mertz
par(mfrow=c(3,3))
plot(settle_04[[2]], xlim=xlim, ylim=ylim, breaks=breaks3, col=cols1, main=paste0("settle_04 ",names(settle_04)[2]))
plot(settle_04[[4]], xlim=xlim, ylim=ylim, breaks=breaks3, col=cols1, main=paste0("settle_04 ",names(settle_04)[4]))
plot(settle_04[[6]], xlim=xlim, ylim=ylim, breaks=breaks3, col=cols1, main=paste0("settle_04 ",names(settle_04)[6]))
plot(settle_06[[2]], xlim=xlim, ylim=ylim, breaks=breaks3, col=cols1, main=paste0("settle_06 ",names(settle_06)[2]))
plot(settle_06[[4]], xlim=xlim, ylim=ylim, breaks=breaks3, col=cols1, main=paste0("settle_06 ",names(settle_06)[4]))
plot(settle_06[[6]], xlim=xlim, ylim=ylim, breaks=breaks3, col=cols1, main=paste0("settle_06 ",names(settle_06)[6]))
plot(settle_08[[2]], xlim=xlim, ylim=ylim, breaks=breaks3, col=cols1, main=paste0("settle_08 ",names(settle_08)[2]))
plot(settle_08[[4]], xlim=xlim, ylim=ylim, breaks=breaks3, col=cols1, main=paste0("settle_08 ",names(settle_08)[4]))
plot(settle_08[[6]], xlim=xlim, ylim=ylim, breaks=breaks3, col=cols1, main=paste0("settle_08 ",names(settle_08)[6]))
```

########## Comparison to Diatom values ##########

```{r, fig.width=10, fig.height=6}
#### Extract flux values at Diatom locations
## circumpolar
surf.vals <- extract(surf_08, polar.dat.diatom)
susp.vals <- extract(susp_08, polar.dat.diatom)
settle.vals <- extract(settle_08, polar.dat.diatom)
diatom.vals <- diatom.dat$Absolute_diatom_abundance_in_million_valves_per_gram_dry_sediment
## Mertz region
surf.vals.m <- extract(surf_08,mertz.diatom.locs)
susp.vals.m <- extract(susp_08,mertz.diatom.locs)
settle.vals.m <- extract(settle_08,mertz.diatom.locs)
diatom.vals.m <- mertz.diatom.dat$Abundance_NO_benthics__valves_g_dry_weight_

#### circumpolar relationship
par(mfrow=c(2,3))
plot(surf.vals[,5], diatom.vals)
plot(susp.vals[,5], diatom.vals)
plot(settle.vals[,5], diatom.vals)
#### compare to Mertz data:
plot(surf.vals.m[,5], diatom.vals.m)
plot(susp.vals.m[,5], diatom.vals.m)
plot(settle.vals.m[,5], diatom.vals.m)

# #### circumpolar relationship
# par(mfrow=c(2,3))
# plot(surf.vals[,5], log(diatom.vals))
# plot(susp.vals[,5], log(diatom.vals))
# plot(settle.vals[,5], log(diatom.vals))
# #### compare to Mertz data:
# plot(surf.vals.m[,5], log(diatom.vals.m))
# plot(susp.vals.m[,5], log(diatom.vals.m))
# plot(settle.vals.m[,5], log(diatom.vals.m))
# library(MASS)
# library(modEvA)
# summary(glm.nb(diatom.vals.m~surf.vals.m))
# summary(glm.nb(diatom.vals.m~susp.vals.m))
# summary(glm.nb(diatom.vals.m~settle.vals.m))
# Dsquared(glm.nb(diatom.vals~surf.vals))
# Dsquared(glm.nb(diatom.vals~susp.vals))
# Dsquared(glm.nb(diatom.vals~settle.vals))
```

```{r, fig.width=10, fig.height=8}
## sort diatom cruises by region
dc.ap.w <- c("DF82","DF86","LMG1311","NBP1001","PD88-III","PD90-7")
dc.ap.e <- c("LMG0502","NBP0003","NBP0603","NBP1203")
dc.ap.both <- c("NBP0107")
dc.eant <- c("NBP1402", "NBP0101")
dc.ross <- c("DF83 III", "NBP9501", "DF83 II", "NBP9401", "PD92")
dc.amund <- "NBP0702"

dat <- data.frame("surf.vals"=surf.vals[,5], "diatom.vals"=diatom.vals)
dat$cruise <- diatom.dat$Cruise
dat$cruise.short <- strtrim(diatom.dat$Cruise,3)
dat$region <- "empty"
dat[diatom.dat$Cruise%in%dc.ap.w,5] <- "ap.w"
dat[diatom.dat$Cruise%in%dc.ap.e,5] <- "ap.e"
dat[diatom.dat$Cruise%in%dc.ap.both,5] <- "ap.both"
dat[diatom.dat$Cruise%in%dc.eant,5] <- "e.eant"
dat[diatom.dat$Cruise%in%dc.ross,5] <- "e.ross"
dat[diatom.dat$Cruise%in%dc.amund,5] <- "e.amund"
dat$reg.cruise <- paste0(dat$region,"_",dat$cruise)

library(dplyr)
dat2 <- arrange(dat, dat$reg.cruise)

library(ggplot2)
ggplot(dat2, aes(x=surf.vals, y=log(diatom.vals), color=region)) +
  geom_point() +
  facet_wrap(~reg.cruise)

ggplot(dat2, aes(x=surf.vals, y=diatom.vals, color=region)) +
  geom_point() +
  facet_wrap(~reg.cruise)

```
