---
title: "Particle tracking - splitting regions"
output: html_document
date: "2024-05-15"
---

```{r}
library(terra)
```

## circumpolar raster

```{r, fig.height=10, fig.width=10}
## set up directory pointers etc
env.dir <- "/pvol/data_environmental/ROMS_2k_files/"
## load bathymetry
h.ra <- rast(paste0(env.dir,"waom2_h.tif"))
```

## regional splits

```{r}
## define objects and empty lists to fill
stereo <- "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"
ra.extents <- list()
ra.2D  <- list()
ra.2Ds <- list()
ra.3D  <- list()
ra.3Ds <- list()
ra.h   <- list()

## load and prepare first region
load(paste0("/pvol/data_environmental/ROMS_2k_files/ocean_his_0001_2slices_TrackingSetup_transposed_distancerunscompleted_1.Rdata"))
x.range <- c(min(Rdat$x)-1000,max(Rdat$x)+1000)
y.range <- c(min(Rdat$y)-1000,max(Rdat$y)+1000)
ra.extents[[1]] <- ext(c(x.range, y.range))
ra.2D[[1]]  <- rast(extent=ra.extents[[1]], crs=stereo, resolution=2000, vals=Rdat$dist2D)
ra.3D[[1]]  <- rast(extent=ra.extents[[1]], crs=stereo, resolution=2000, vals=Rdat$dist3D)
ra.2Ds[[1]] <- rast(extent=ra.extents[[1]], crs=stereo, resolution=2000, vals=Rdat$dist2Ds)
ra.3Ds[[1]] <- rast(extent=ra.extents[[1]], crs=stereo, resolution=2000, vals=Rdat$dist3Ds)
ra.h[[1]]   <- rast(extent=ra.extents[[1]], crs=stereo, resolution=2000, vals=Rdat$h)

## repeat for all others
for(i in 2:10){
  load(paste0("/pvol/data_environmental/ROMS_2k_files/ocean_his_0001_2slices_TrackingSetup_transposed_distancerunscompleted_",i,".Rdata"))
  x.range <- c(min(Rdat$x)-1000,max(Rdat$x)+1000)
  y.range <- c(min(Rdat$y)-1000,max(Rdat$y)+1000)

  ra.extents[[i]] <- ext(c(x.range, y.range))
  ra.2D[[i]]  <- rast(extent=ra.extents[[i]], crs=stereo, resolution=2000, vals=Rdat$dist2D)
  ra.3D[[i]]  <- rast(extent=ra.extents[[i]], crs=stereo, resolution=2000, vals=Rdat$dist3D)
  ra.2Ds[[i]] <- rast(extent=ra.extents[[i]], crs=stereo, resolution=2000, vals=Rdat$dist2Ds)
  ra.3Ds[[i]] <- rast(extent=ra.extents[[i]], crs=stereo, resolution=2000, vals=Rdat$dist3Ds)
  ra.h[[i]]   <- rast(extent=ra.extents[[i]], crs=stereo, resolution=2000, vals=Rdat$h)
}

range2D <- c(0,500000)
range3D <- c(0,600000)
```


```{r, fig.dim=c(10,10)}
plot(h.ra, main="2D final pos, dist to start", legend=FALSE)
plot(ra.2D[[10]], add=TRUE, range=range2D)
contour(ra.h[[10]], levels=1500, add=TRUE, lty=2)
for(i in 1:9){
  plot(ra.2D[[i]], add=TRUE, range=range2D, legend=FALSE)
  contour(ra.h[[i]], levels=1500, add=TRUE, lty=2)
}
```

```{r, fig.dim=c(10,10)}
plot(h.ra, main="2D start pos, dist to final", legend=FALSE)
plot(ra.2Ds[[10]], add=TRUE, range=range2D)
contour(ra.h[[10]], levels=1500, add=TRUE, lty=2)
for(i in 1:9){
  plot(ra.2Ds[[i]], add=TRUE, range=range2D, legend=FALSE)
  contour(ra.h[[i]], levels=1500, add=TRUE, lty=2)
}
```

```{r, fig.dim=c(10,10)}
plot(h.ra, main="3D final pos, dist to start", legend=FALSE)
plot(ra.3D[[10]], add=TRUE, range=range3D)
contour(ra.h[[10]], levels=1500, add=TRUE, lty=2)
for(i in 1:9){
  plot(ra.3D[[i]], add=TRUE, range=range3D, legend=FALSE)
  contour(ra.h[[i]], levels=1500, add=TRUE, lty=2)
}
```

```{r, fig.dim=c(10,10)}
plot(h.ra, main="3D start pos, dist to final", legend=FALSE)
plot(ra.3Ds[[10]], add=TRUE, range=range3D)
contour(ra.h[[10]], levels=1500, add=TRUE, lty=2)
for(i in 1:9){
  plot(ra.3Ds[[i]], add=TRUE, range=range3D, legend=FALSE)
  contour(ra.h[[i]], levels=1500, add=TRUE, lty=2)
}
```


## new suggested boundaries

```{r}
load(paste0(env.dir,"ocean_his_0001_2slices_TrackingSetup_transposed.Rdata"))
## reduce the ROMS by excluding areas that are not relevant for the shelf, such as North of the Ross Sea
Rdat <- ROMS_2k_t

roms.coords.proj <- cbind(c(Rdat$x), c(Rdat$y))
x.range <- c(min(roms.coords.proj[,1])-1000,max(roms.coords.proj[,1])+1000)
y.range <- c(min(roms.coords.proj[,2])-1000,max(roms.coords.proj[,2])+1000)
empty.roms.ra <- rast(extent=ext(c(x.range,y.range)), crs=stereo, resolution=2000)

uv.ra      <- setValues(empty.roms.ra, sqrt(Rdat$i_u[,,1,1]^2 +c(Rdat$i_v[,,1,1])^2))
h.ra       <- setValues(empty.roms.ra, Rdat$h)
h.ra[is.na(uv.ra[])] <- NA
rm(ROMS_2k_t)
```


```{r, fig.dim=c(10,10)}
lim <- matrix(NA, nrow=4, ncol=10)
lim[,1] <- c(1751,2400,1201,1800) ## Ross Sea           650 x 600 = 390k
lim[,2] <- c(1701,2100,401,1300)  ## Amundsen Sea       400 x 900 = 360k
lim[,3] <- c(851,1800,201,760)    ## Bellinghausen Sea  950 x 560 = 532k
lim[,4] <- c(1,900,51,600)        ## Peninsula          900 x 550 = 495k
lim[,5] <- c(401,1000,401,1300)   ## Weddell            800 x 800 = 640k
lim[,6] <- c(1,550,1101,2500)     ## Lazarev            550 x 1300= 715k
lim[,7] <- c(351,1300,2401,2900)   ## Amery             900 x 500 = 450k
lim[,8] <- c(1201,2100,2501,3000)   ## Mawson           900 x 500 = 450k
lim[,9] <- c(2001,2600,1901,2700)   ## D'Urville        600 x 800 = 480k
lim[,10] <- c(2301,2650,1301,2000)   ## Seamounts       350 x 700 = 245k
ext.list <- list()
ext.list[[1]]  <- ext(Rdat$x[lim[1,1], lim[3,1]],  Rdat$x[lim[1,1], lim[4,1]],  Rdat$y[lim[2,1], lim[3,1]],  Rdat$y[lim[1,1], lim[3,1]])
ext.list[[2]]  <- ext(Rdat$x[lim[1,2], lim[3,2]],  Rdat$x[lim[1,2], lim[4,2]],  Rdat$y[lim[2,2], lim[3,2]],  Rdat$y[lim[1,2], lim[3,2]])
ext.list[[3]]  <- ext(Rdat$x[lim[1,3], lim[3,3]],  Rdat$x[lim[1,3], lim[4,3]],  Rdat$y[lim[2,3], lim[3,3]],  Rdat$y[lim[1,3], lim[3,3]])
ext.list[[4]]  <- ext(Rdat$x[lim[1,4], lim[3,4]],  Rdat$x[lim[1,4], lim[4,4]],  Rdat$y[lim[2,4], lim[3,4]],  Rdat$y[lim[1,4], lim[3,4]])
ext.list[[5]]  <- ext(Rdat$x[lim[1,5], lim[3,5]],  Rdat$x[lim[1,5], lim[4,5]],  Rdat$y[lim[2,5], lim[3,5]],  Rdat$y[lim[1,5], lim[3,5]])
ext.list[[6]]  <- ext(Rdat$x[lim[1,6], lim[3,6]],  Rdat$x[lim[1,6], lim[4,6]],  Rdat$y[lim[2,6], lim[3,6]],  Rdat$y[lim[1,6], lim[3,6]])
ext.list[[7]]  <- ext(Rdat$x[lim[1,7], lim[3,7]],  Rdat$x[lim[1,7], lim[4,7]],  Rdat$y[lim[2,7], lim[3,7]],  Rdat$y[lim[1,7], lim[3,7]])
ext.list[[8]]  <- ext(Rdat$x[lim[1,8], lim[3,8]],  Rdat$x[lim[1,8], lim[4,8]],  Rdat$y[lim[2,8], lim[3,8]],  Rdat$y[lim[1,8], lim[3,8]])
ext.list[[9]]  <- ext(Rdat$x[lim[1,9], lim[3,9]],  Rdat$x[lim[1,9], lim[4,9]],  Rdat$y[lim[2,9], lim[3,9]],  Rdat$y[lim[1,9], lim[3,9]])
ext.list[[10]] <- ext(Rdat$x[lim[1,10],lim[3,10]], Rdat$x[lim[1,10],lim[4,10]], Rdat$y[lim[2,10],lim[3,10]], Rdat$y[lim[1,10],lim[3,10]])
```


```{r, fig.dim=c(10,10)}
plot(h.ra, main="2D final pos, dist to start", legend=FALSE)
plot(ra.2D[[1]], add=TRUE, range=range2D)
contour(ra.h[[1]], levels=1500, add=TRUE, lty=2)
lines(ext.list[[1]])
for(i in 2:10){
 plot(ra.2D[[i]], add=TRUE, range=range2D, legend=FALSE)
 contour(ra.h[[i]], levels=1500, add=TRUE, lty=2)
 lines(ext.list[[i]])
}
```



## 11 regions:

```{r, fig.dim=c(10,10)}
lim <- matrix(NA, nrow=4, ncol=10)
lim[,1] <- c(1751,2500,1101,1800) ## Ross Sea            750 x  700 = 525k
lim[,2] <- c(1601,2100,401,1300)  ## Amundsen Sea        500 x  900 = 450k
lim[,3] <- c(901,1800,201,760)    ## Bellinghausen Sea   900 x  560 = 504k
lim[,4] <- c(1,1100,1,650)        ## Peninsula          1100 x  650 = 715k
lim[,5] <- c(351,1000,401,1300)   ## Weddell             650 x  900 = 585k
lim[,6] <- c(1,550,1001,2500)     ## Lazarev             550 x 1500 = 825k
lim[,7] <- c(301,1300,2301,2900)   ## Amery             1000 x  600 = 600k
lim[,8] <- c(1101,2100,2501,3000)   ## Mawson           1000 x  500 = 500k
lim[,9] <- c(1901,2600,2001,2700)   ## D'Urville         700 x  700 = 490k
lim[,10] <- c(2251,2700,1301,2200)   ## Seamounts&Cook   450 x  700 = 315k
ext.list <- list()
ext.list[[1]]  <- ext(Rdat$x[lim[1,1], lim[3,1]],  Rdat$x[lim[1,1], lim[4,1]],  Rdat$y[lim[2,1], lim[3,1]],  Rdat$y[lim[1,1], lim[3,1]])
ext.list[[2]]  <- ext(Rdat$x[lim[1,2], lim[3,2]],  Rdat$x[lim[1,2], lim[4,2]],  Rdat$y[lim[2,2], lim[3,2]],  Rdat$y[lim[1,2], lim[3,2]])
ext.list[[3]]  <- ext(Rdat$x[lim[1,3], lim[3,3]],  Rdat$x[lim[1,3], lim[4,3]],  Rdat$y[lim[2,3], lim[3,3]],  Rdat$y[lim[1,3], lim[3,3]])
ext.list[[4]]  <- ext(Rdat$x[lim[1,4], lim[3,4]],  Rdat$x[lim[1,4], lim[4,4]],  Rdat$y[lim[2,4], lim[3,4]],  Rdat$y[lim[1,4], lim[3,4]])
ext.list[[5]]  <- ext(Rdat$x[lim[1,5], lim[3,5]],  Rdat$x[lim[1,5], lim[4,5]],  Rdat$y[lim[2,5], lim[3,5]],  Rdat$y[lim[1,5], lim[3,5]])
ext.list[[6]]  <- ext(Rdat$x[lim[1,6], lim[3,6]],  Rdat$x[lim[1,6], lim[4,6]],  Rdat$y[lim[2,6], lim[3,6]],  Rdat$y[lim[1,6], lim[3,6]])
ext.list[[7]]  <- ext(Rdat$x[lim[1,7], lim[3,7]],  Rdat$x[lim[1,7], lim[4,7]],  Rdat$y[lim[2,7], lim[3,7]],  Rdat$y[lim[1,7], lim[3,7]])
ext.list[[8]]  <- ext(Rdat$x[lim[1,8], lim[3,8]],  Rdat$x[lim[1,8], lim[4,8]],  Rdat$y[lim[2,8], lim[3,8]],  Rdat$y[lim[1,8], lim[3,8]])
ext.list[[9]]  <- ext(Rdat$x[lim[1,9], lim[3,9]],  Rdat$x[lim[1,9], lim[4,9]],  Rdat$y[lim[2,9], lim[3,9]],  Rdat$y[lim[1,9], lim[3,9]])
ext.list[[10]] <- ext(Rdat$x[lim[1,10],lim[3,10]], Rdat$x[lim[1,10],lim[4,10]], Rdat$y[lim[2,10],lim[3,10]], Rdat$y[lim[1,10],lim[3,10]])
```


```{r, fig.dim=c(10,10)}
plot(h.ra, main="2D final pos, dist to start", legend=FALSE)
plot(ra.2D[[1]], add=TRUE, range=range2D)
contour(ra.h[[1]], levels=c(1500,2500), add=TRUE, lty=2)
lines(ext.list[[1]])
for(i in 2:10){
 plot(ra.2D[[i]], add=TRUE, range=range2D, legend=FALSE)
 contour(ra.h[[i]], levels=c(1500,2500), add=TRUE, lty=2)
 lines(ext.list[[i]])
}
```






































```{r, eval=FALSE, echo=FALSE}
#############################################################
#############################################################
## Analyse outputs:
#############################################################
stereo <- "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"

ra.extents <- list()
for(i in 1:10){
  print(i)
  load(paste0("/pvol/data_environmental/ROMS_2k_files/ocean_his_0001_2slices_TrackingSetup_transposed_distancerunscompleted_",i,".Rdata"))
  x.range <- c(min(Rdat$x)-1000,max(Rdat$x)+1000)
  y.range <- c(min(Rdat$y)-1000,max(Rdat$y)+1000)
  ra.extents[[i]] <- ext(c(x.range, y.range))
}

ra_setup_and_plot <- function(k){
  ## load data
  load(paste0("/pvol/data_environmental/ROMS_2k_files/ocean_his_0001_2slices_TrackingSetup_transposed_distancerunscompleted_",k,".Rdata"))
  dist.2D  <- rast(extent=ra.extents[[k]], crs=stereo, resolution=2000, vals=Rdat$dist2D)
  dist.3D  <- rast(extent=ra.extents[[k]], crs=stereo, resolution=2000, vals=Rdat$dist3D)
  dist.2Ds <- rast(extent=ra.extents[[k]], crs=stereo, resolution=2000, vals=Rdat$dist2Ds)
  dist.3Ds <- rast(extent=ra.extents[[k]], crs=stereo, resolution=2000, vals=Rdat$dist3Ds)
  h2.ra     <- rast(extent=ra.extents[[k]], crs=stereo, resolution=2000, vals=Rdat$h)

  ## choose which boundaries to add to the plot
  if(k==1){
    sel <- c(10,2)
  } else if(k==10){
    sel <- c(9,1)
  } else sel <- c(k-1, k+1)
  
  ## plot
  par(mfrow=c(2,2), mar=c(3,4,3,2))
  plot(dist.2D,  main="2D final pos, dist to start", range=c(0,500000))
  contour(h2.ra, levels=1500, add=TRUE, lty=2)
  lines(ra.extents[[sel[1]]], lty=2)
  lines(ra.extents[[sel[2]]], lty=2)
  plot(dist.2Ds, main="2D start pos, dist to final", range=c(0,500000))
  contour(h2.ra, levels=1500, add=TRUE, lty=2)
  lines(ra.extents[[sel[1]]], lty=2)
  lines(ra.extents[[sel[2]]], lty=2)
  plot(dist.3D,  main="3D final pos, dist to start", range=c(0,600000))
  contour(h2.ra, levels=1500, add=TRUE, lty=2)
  lines(ra.extents[[sel[1]]], lty=2)
  lines(ra.extents[[sel[2]]], lty=2)
  plot(dist.3Ds, main="3D start pos, dist to final", range=c(0,600000))
  contour(h2.ra, levels=1500, add=TRUE, lty=2)
  lines(ra.extents[[sel[1]]], lty=2)
  lines(ra.extents[[sel[2]]], lty=2)
  # par(mfrow=c(1,1))
  # plot(dist.3Ds, main="3D start pos, dist to final")
  # contour(h.ra, levels=1500, add=TRUE, lty=2)
}
```

```{r, eval=FALSE, echo=FALSE}
## 1
ra_setup_and_plot(1)
ra_setup_and_plot(2)
ra_setup_and_plot(3)
ra_setup_and_plot(4) ## AP
ra_setup_and_plot(5) ## Weddell
ra_setup_and_plot(6)
ra_setup_and_plot(7)
ra_setup_and_plot(8)
ra_setup_and_plot(9)
ra_setup_and_plot(10)
```

```{r, eval=FALSE, echo=FALSE}
load(paste0("/pvol/data_environmental/ROMS_2k_files/ocean_his_0001_2slices_TrackingSetup_transposed_distancerunscompleted_1.Rdata"))
dist.2D  <- rast(extent=ra.extents[[1]], crs=stereo, resolution=2000, vals=Rdat$dist2D)
dist.3D  <- rast(extent=ra.extents[[1]], crs=stereo, resolution=2000, vals=Rdat$dist3D)
dist.2Ds <- rast(extent=ra.extents[[1]], crs=stereo, resolution=2000, vals=Rdat$dist2Ds)
dist.3Ds <- rast(extent=ra.extents[[1]], crs=stereo, resolution=2000, vals=Rdat$dist3Ds)
h2.ra    <- rast(extent=ra.extents[[1]], crs=stereo, resolution=2000, vals=Rdat$h)

for(k in 2:10){
  load(paste0("/pvol/data_environmental/ROMS_2k_files/ocean_his_0001_2slices_TrackingSetup_transposed_distancerunscompleted_",k,".Rdata"))
  dist.2D  <- c(dist.2D,  rast(extent=ra.extents[[k]], crs=stereo, resolution=2000, vals=Rdat$dist2D))
  dist.3D  <- c(dist.2Ds, rast(extent=ra.extents[[k]], crs=stereo, resolution=2000, vals=Rdat$dist3D))
  dist.2Ds <- c(dist.3D,  rast(extent=ra.extents[[k]], crs=stereo, resolution=2000, vals=Rdat$dist2Ds))
  dist.3Ds <- c(dist.3Ds, rast(extent=ra.extents[[k]], crs=stereo, resolution=2000, vals=Rdat$dist3Ds))
  h2.ra    <- c(h2.ra,    rast(extent=ra.extents[[k]], crs=stereo, resolution=2000, vals=Rdat$h))
}
```

